- name: all hosts install
  hosts: myhosts
  become: true
  tasks:
    - name: postgresql instalation
      package:
        name: postgresql
        state: present
    - name: psycopg instalation
      package:
        name: postgresql-contrib
        state: present
    - name: libpq-dev instalation
      package:
        name: libpq-dev
        state: present

- name: instalation for host1
  hosts: host1
  become: true
  tasks:
    - name: cloning a git repository
      git:
        repo: "{{ hostvars[inventory_hostname]['GIT'] }}"
        dest: "{{ hostvars[inventory_hostname]['WORKDIR'] }}"
        version: main
    - name: install pip3
      package:
        name: python3-pip
        state: present
    - name: installing pip packages
      pip:
        requirements: "{{ hostvars[inventory_hostname]['WORKDIR'] }}/requirements.txt"
    - name: make logs dir
      command: mkdir -p "{{ hostvars[inventory_hostname]['WORKDIR'] }}/../bot"
    - name: postgresql.conf master configuration
      blockinfile:
        path: "/etc/postgresql/{{ hostvars[inventory_hostname]['POSTGRES_VERSION'] }}/main/postgresql.conf"
        block: |
          listen_addresses = '*'
          port = {{ hostvars[inventory_hostname]['DB_PORT'] }}
          archive_mode = on
          archive_command = 'cp %p /oracle/pg_data/archive/%f'
          max_wal_senders=10
          wal_level=replica
          wal_log_hints = on
          hot_standby=on
          max_replication_slots=10
          hot_standby_feedback=on
          log_replication_commands=on
    - name: pg_hba.conf master configuration
      blockinfile:
        path: "/etc/postgresql/{{ hostvars[inventory_hostname]['POSTGRES_VERSION'] }}/main/pg_hba.conf"
        block: |
          local all postgres peer
          host replication all {{ hostvars[inventory_hostname]['ansible_host'] }}/24 scram-sha-256
          host all all {{ hostvars[inventory_hostname]['ansible_host'] }}/32 trust
    - name: applying changes
      service:
        name: postgresql
        state: restarted
    - name: create new user
      command: psql -c "ALTER ROLE postgres PASSWORD 'Qq12345';"
      become: true
      become_user: postgres
    - name: copying init.sql
      copy:
        src: init.sql
        dest: /tmp/init.sql
    - name: change of rights
      file:
        path: /tmp/init.sql
        owner: postgres
        group: postgres
        mode: '0644'
    - name: db init
      replace:
        path: /tmp/init.sql
        regexp: "DB_DATABASE"
        replace: "{{ hostvars[inventory_hostname]['DB_DATABASE'] }}"
    - name: user init
      replace:
        path: /tmp/init.sql
        regexp: "DB_USER"
        replace: "{{ hostvars[inventory_hostname]['DB_USER'] }}"
    - name: repl user init
      replace:
        path: /tmp/init.sql
        regexp: "DB_REPL_USER"
        replace: "{{ hostvars[inventory_hostname]['DB_REPL_USER'] }}"
    - name: repl password init
      replace:
        path: /tmp/init.sql
        regexp: "DB_REPL_PASSWORD"
        replace: "{{ hostvars[inventory_hostname]['DB_REPL_PASSWORD'] }}"
    - name: run init.sql
      command: /usr/bin/psql -a -f /tmp/init.sql
      become: true
      become_user: postgres

- name: instalation for host2
  hosts: host2
  become: true
  tasks:
    - name: postgresql.conf slave configuration
      blockinfile:
        path: "/etc/postgresql/{{ hostvars[inventory_hostname]['POSTGRES_VERSION'] }}/main/postgresql.conf"
        block: |
          listen_addresses = '*'
          port = {{ hostvars[inventory_hostname]['DB_REPL_PORT'] }}
      become: true
      become_user: postgres
    - name: applying slave changes
      service:
        name: postgresql
        state: restarted
    - name: deleting databases
      command: rm -rf /var/lib/postgresql/{{ hostvars[inventory_hostname]['POSTGRES_VERSION'] }}/
      become: true
      become_user: postgres
    - name: performing replication
      command: pg_basebackup -h {{ hostvars[inventory_hostname]['DB_HOST'] }} -D /var/lib/postgresql/{{ hostvars[inventory_hostname]['POSTGRES_VERSION'] }}/main/ -p {{ hostvars[inventory_hostname]['DB_PORT'] }} -U {{ hostvars[inventory_hostname]['DB_REPL_USER'] }} -vP -w
      become: true
      become_user: postgres
      environment:
        PGPASSWORD: "{{ hostvars[inventory_hostname]['DB_REPL_PASSWORD'] }}"
    - name: change of rights
      command: chown -R postgres:postgres /var/lib/postgresql/
      become: true
      become_user: postgres

- name: bot start
  hosts: host1
  become: true
  tasks:        
    - name: launch a bot
      command: python3 "{{ hostvars[inventory_hostname]['WORKDIR'] }}/bot.py"
      environment:
        TOKEN: "{{ hostvars[inventory_hostname]['TOKEN'] }}"
        HOST: "{{ hostvars[inventory_hostname]['RM_HOST'] }}"
        PORT: "{{ hostvars[inventory_hostname]['RM_PORT'] }}"
        USER: "{{ hostvars[inventory_hostname]['RM_USER'] }}"
        PASSWORD: "{{ hostvars[inventory_hostname]['RM_PASSWORD'] }}"
        DBHOST: "{{ hostvars[inventory_hostname]['DB_HOST'] }}"
        DBPORT: "{{ hostvars[inventory_hostname]['DB_PORT'] }}"
        DBUSER: "{{ hostvars[inventory_hostname]['DB_USER'] }}"
        DBPASSWORD: "{{ hostvars[inventory_hostname]['DB_PASSWORD'] }}"
        DBNAME: "{{ hostvars[inventory_hostname]['DB_DATABASE'] }}"
   
